FROM python:3.9.18-bullseye
WORKDIR /app
COPY requirements.txt .
RUN python3 -m pip install -i https://mirrors.aliyun.com/pypi/simple -r requirements.txt
COPY . .
# CMD ["uvicorn", "application.asgi:application", "--port", "8000", "--host", "0.0.0.0", "--workers", "4"]
CMD ["gunicorn","-c","gunicorn_conf.py", "application.asgi:application"]