# Generated by Django 3.2.19 on 2024-05-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslmonitors',
            name='ssl_expire_days',
            field=models.IntegerField(help_text='过期天数', max_length=255, null=True, verbose_name='过期天数'),
        ),
    ]
