# Generated by Django 3.2.19 on 2024-05-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0002_alter_sslmonitors_ssl_expire_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainMonitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='域名名称', max_length=255, null=True, verbose_name='域名名称')),
                ('domain_status', models.CharField(help_text='域名状态', max_length=255, null=True, verbose_name='域名状态')),
                ('domain_expire_time', models.DateTimeField(help_text='域名过期时间', max_length=255, null=True, verbose_name='域名过期时间')),
                ('domain_expire_days', models.IntegerField(help_text='域名过期天数', null=True, verbose_name='域名过期天数')),
                ('domain_account', models.CharField(help_text='域名所在账号', max_length=255, null=True, verbose_name='域名所在账号')),
                ('domain_notice_enable', models.BooleanField(default=True, help_text='是否开启通知', null=True, verbose_name='是否开启通知')),
                ('doman_remark', models.CharField(help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('insert_time', models.DateTimeField(auto_now_add=True, help_text='插入时间', null=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'monitors_domain',
            },
        ),
        migrations.AlterField(
            model_name='sslmonitors',
            name='ssl_expire_days',
            field=models.IntegerField(help_text='过期天数', null=True, verbose_name='过期天数'),
        ),
    ]
