# Generated by Django 4.2.13 on 2025-01-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0003_auto_20240520_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslmonitors',
            name='web_check_enable',
            field=models.BooleanField(default=True, help_text='网站检查是否开启', null=True, verbose_name='网站检查是否开启'),
        ),
        migrations.AddField(
            model_name='sslmonitors',
            name='web_http_enable',
            field=models.BooleanField(default=True, help_text='网站HTTP检查是否开启', null=True, verbose_name='网站HTTP检查是否开启'),
        ),
        migrations.AddField(
            model_name='sslmonitors',
            name='web_https_enable',
            field=models.BooleanField(default=True, help_text='网站HTTPS检查是否开启', null=True, verbose_name='网站HTTPS检查是否开启'),
        ),
        migrations.AddField(
            model_name='sslmonitors',
            name='web_notice_enable',
            field=models.BooleanField(default=True, help_text='网站通知是否开启', null=True, verbose_name='网站通知是否开启'),
        ),
        migrations.AddField(
            model_name='sslmonitors',
            name='web_status',
            field=models.CharField(help_text='网站状态', max_length=255, null=True, verbose_name='网站状态'),
        ),
    ]
