# Generated by Django 4.2.13 on 2025-01-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0004_sslmonitors_web_check_enable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslmonitors',
            name='web_status',
            field=models.CharField(default='正常', help_text='网站状态', max_length=255, null=True, verbose_name='网站状态'),
        ),
    ]
