# Generated by Django 4.2.13 on 2025-01-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0006_webmonitors_remove_sslmonitors_web_check_enable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebMonitorsResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_uri', models.CharField(help_text='网站URI', max_length=255, null=True, verbose_name='网站URI')),
                ('web_status', models.CharField(help_text='网站状态', max_length=255, null=True, verbose_name='网站状态')),
                ('web_http_status', models.BooleanField(help_text='网站HTTP状态', null=True, verbose_name='网站HTTP状态')),
                ('web_https_status', models.BooleanField(help_text='网站HTTPS状态', null=True, verbose_name='网站HTTPS状态')),
                ('web_http_response_time', models.FloatField(help_text='网站HTTP响应时间', null=True, verbose_name='网站HTTP响应时间')),
                ('web_https_response_time', models.FloatField(help_text='网站HTTPS响应时间', null=True, verbose_name='网站HTTPS响应时间')),
                ('insert_time', models.DateTimeField(auto_now_add=True, help_text='插入时间', null=True, verbose_name='插入时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
            ],
            options={
                'db_table': 'monitors_web_result',
            },
        ),
    ]
