# Generated by Django 4.2.13 on 2025-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitors', '0007_webmonitorsresult'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='webmonitorsresult',
            index=models.Index(fields=['web_uri'], name='web_uri_idx'),
        ),
        migrations.AddIndex(
            model_name='webmonitorsresult',
            index=models.Index(fields=['insert_time'], name='insert_time_idx'),
        ),
    ]
