# Generated by Django 4.2.13 on 2024-07-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k8s_cluster_name', models.CharField(blank=True, help_text='k8s_cluster_name', max_length=255, verbose_name='k8s_cluster_name')),
                ('k8s_clustet_desc', models.CharField(blank=True, help_text='k8s_clustet_desc', max_length=255, verbose_name='k8s_clustet_desc')),
                ('k8s_cluster_config', models.TextField(blank=True, help_text='k8s_cluster_config', verbose_name='k8s_cluster_config')),
                ('k8s_exclude_namespace', models.CharField(help_text='k8s_exclude_namespace', max_length=255, verbose_name='k8s_exclude_namespace')),
            ],
            options={
                'db_table': 'container_k8s_cluster',
                'ordering': ['id'],
            },
        ),
    ]
