# Generated by Django 4.2.13 on 2024-07-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_k8scluster_k8s_cluster_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='k8scluster',
            name='k8s_default_namespace',
            field=models.CharField(blank=True, help_text='k8s_default_namespace', max_length=255, verbose_name='k8s_default_namespace'),
        ),
    ]
