# Generated by Django 4.2.13 on 2024-08-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_alter_k8scluster_k8s_default_namespace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='k8scluster',
            name='k8s_cluster_is_default',
            field=models.BooleanField(blank=True, default=False, help_text='k8s_cluster_is_default', verbose_name='k8s_cluster_is_default'),
        ),
        migrations.AlterField(
            model_name='k8scluster',
            name='k8s_exclude_namespace',
            field=models.CharField(blank=True, help_text='k8s_exclude_namespace', max_length=255, verbose_name='k8s_exclude_namespace'),
        ),
    ]
