# Generated by Django 3.2.19 on 2024-05-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_sslmonitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sslmonitors',
            name='ssl_expire_date',
            field=models.CharField(help_text='过期天数', max_length=255, null=True, verbose_name='过期天数'),
        ),
    ]
