# Generated by Django 3.2.19 on 2024-05-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_sslmonitors_ssl_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslmonitors',
            name='ssl_expire_time',
            field=models.DateTimeField(help_text='过期时间', max_length=255, null=True, verbose_name='过期时间'),
        ),
    ]
