# Generated by Django 3.2.19 on 2024-05-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_alter_sslmonitors_ssl_expire_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sslmonitors',
            old_name='ssl_expire_date',
            new_name='ssl_expire_days',
        ),
    ]
