# Generated by Django 3.2.19 on 2024-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_sslmonitors_ssl_notice_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sslmonitors',
            name='ssl_notice_enable',
            field=models.BooleanField(default=True, help_text='是否开启通知', null=True, verbose_name='是否开启通知'),
        ),
    ]
