# Generated by Django 3.2.19 on 2024-05-11 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0007_alter_sslmonitors_ssl_notice_enable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSLMonitors',
        ),
    ]
